<?php

namespace Container0SSbAxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3BVcuJzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3BVcuJz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3BVcuJz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'session' => ['privates', '.errored..service_locator.3BVcuJz.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.3BVcuJz": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists. Try changing the type-hint to "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface" instead.'],
            'translator' => ['privates', 'App\\Services\\TranslatorService', 'getTranslatorServiceService', true],
        ], [
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
            'translator' => 'App\\Services\\TranslatorService',
        ]);
    }
}
