<?php

namespace Container9YHM0nc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oly8gQ8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oly8gQ8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oly8gQ8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'session' => ['privates', '.errored..service_locator.oly8gQ8.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.oly8gQ8": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists. Try changing the type-hint to "Symfony\\Component\\HttpFoundation\\Session\\SessionInterface" instead.'],
            'translator' => ['privates', '.errored..9GnfAE', NULL, 'Cannot determine controller argument for "App\\Controller\\BankRouletteController::indexAction()": the $translator argument is type-hinted with the non-existent class or interface: "App\\Controller\\TranslatorService". Did you forget to add a use statement?'],
        ], [
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
            'translator' => '?',
        ]);
    }
}
