<?php

namespace Container9YHM0nc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranslatorServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\TranslatorService' shared autowired service.
     *
     * @return \App\Services\TranslatorService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/TranslatorService.php';
        include_once \dirname(__DIR__, 4).'/src/Utils/Configuration.php';

        return $container->privates['App\\Services\\TranslatorService'] = new \App\Services\TranslatorService(($container->services['session'] ?? $container->load('getSessionService')), new \App\Utils\Configuration());
    }
}
