<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0SSbAxD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0SSbAxD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0SSbAxD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0SSbAxD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0SSbAxD\App_KernelDevDebugContainer([
    'container.build_hash' => '0SSbAxD',
    'container.build_id' => 'ec032ff7',
    'container.build_time' => 1614841653,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0SSbAxD');
