<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'lobby' => [[], ['_controller' => 'App\\Controller\\BankRouletteController::indexAction'], [], [['text', '/lobby']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\DefaultController::indexAction'], [], [['text', '/']], [], []],
    'lang' => [['locale'], ['_controller' => 'App\\Controller\\DefaultController::changeLangAction'], [], [['variable', '/', '[^/]++', 'locale', true], ['text', '/lng']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::loginAction'], [], [['text', '/login']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logoutAction'], [], [['text', '/logout']], [], []],
    'fast_registration' => [[], ['_controller' => 'App\\Controller\\UsersController::fastregistrationAction'], [], [['text', '/fastregistration']], [], []],
    'user_search' => [[], ['_controller' => 'App\\Controller\\UsersController::searchAction'], [], [['text', '/usersearch']], [], []],
];
